controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - pan_joint
    interface_name: angle
